;;; Uncomment the modules you'd like to use and restart Prelude afterwards

;; Emacs IRC client
(require 'prelude-erc)
(require 'prelude-ido) ;; Super charges Emacs completion for C-x C-f and more
(require 'prelude-helm) ;; Interface for narrowing and search
;; (require 'prelude-helm-everywhere) ;; Enable Helm everywhere
(require 'prelude-company)
;; (require 'prelude-key-chord) ;; Binds useful features to key combinations
;; (require 'prelude-mediawiki)
;; (require 'prelude-evil)

;;; Programming languages support
(require 'prelude-c)
(require 'prelude-clojure)
;; (require 'prelude-coffee)
(require 'prelude-common-lisp)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
;; (require 'prelude-erlang)
(require 'prelude-elixir)
(require 'prelude-go)
(require 'prelude-haskell)
(require 'prelude-js)
(require 'prelude-latex)
(require 'prelude-lisp)
;; (require 'prelude-ocaml)
(require 'prelude-org) ;; Org-mode helps you keep TODO lists, notes and more
(require 'prelude-perl)
(require 'prelude-python)
(require 'prelude-ruby)
(require 'prelude-rust)
;; (require 'prelude-scala)
(require 'prelude-scheme)
(require 'prelude-shell)
(require 'prelude-scss)
(require 'prelude-web) ;; Emacs mode for web templates
(require 'prelude-xml)
(require 'prelude-yaml)
(require 'prelude-xml)
(require 'prelude-key-chord)
(require 'prelude-more-textx)
(require 'prelude-more-adoc)
(require 'prelude-more-diary)
(require 'prelude-more-org-pages)
(require 'prelude-more-plantuml)
(require 'prelude-more-docker)
(require 'prelude-more-wttrin)
(require 'prelude-more-sparql)
(require 'prelude-more-w3m)
(require 'prelude-more-helm-dash)
;; (require 'prelude-more-slack)
(require 'prelude-more-time-management)
(require 'prelude-more-debugging)
(require 'prelude-more-hackernews)
(require 'prelude-more-languagetool)
;; (require 'prelude-more-llvm)
;; (require 'prelude-more-proofgeneral)
(require 'prelude-more-org-gcal)
;; (require 'prelude-more-alloy)
(require 'prelude-more-verilog)
;; (require 'prelude-more-tla-plus)
(require 'prelude-more-yasnippet)
